language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - # GRADLE PLUGINS Environment variables for deployment 
  - secure: NYGzCnBjHYOh+MvfmypkmLQSJxPTy1532NzWtzF17eA8RpCJfqNg+WuhOW07IU7g5Y+BI1wVQubd/39R1VTVmhzWWQJxXDTu96toOg4YD89v/sGmK7RWjac4IFAdPpgtA9oSJ9YUV5lRCDA/NK1/GfLQsUrJ5wjblC0ppc0S6G5ZXu7zcuaFDH1WMAWw9pxrmXukuTqIaPnMPVkGpi0R8BPmut8vq3oX/UAoCucB4raOWd5TbsxS5enD7rwlFQjl1/wMNF880t2uQah1xHWcySeESE4Ue5KIMlbXRqo6sbaYnbC/htsUugQuXW2C6vuWvqvWFplaRPEesDtFONDtxpI7URKiXxspM7bShUAxlsNXqiX/wqvVb3BM7R/gm/grJeGdq9GHWnLNC9yL+hPJuB/iXE6z3Ortqn2bT6ONiUFVIQpJ/X5CjHIAXatg0hluSQk6mu6ba0dKq1D/gsCkx1O+5G4WwcvhiRplfO1SHqs47sCGY71zSd594u3gOBmC1q5tpBLz4k2xXnjoezqTcRqv27FcLOTq06EW1iJ42dHe1UYS4qOxF+NUt4/AAVe3TBry+P7d9ZvkWlEoXd5T2AlpR+l7ovcxSdQByV6nm+MgLMfKyNMDgtXHSNe7oDd6dFycHqR2jKtykYpdBQf0473ZxYzNFiZsapeqPDsjrmk=
  - secure: mTEnUL1m2LrLybNm1FhaaWUukesOmHh3kqMqXZYG0mVojmyybc+TBOznho7CG9wGFMbX6ksrkxBhPwmDxAX2GXFIXTJzPr1ChZbN7P0xKN4rQX/J9+30aPBONHDwmAJUaVK7wi6IYLEBFptnkz0sQt0IkY0YOEn/CyqIK0/XKE5krsTEJP2rKvpDP1WTRD8mmBmkjVGvC7DpJrXJZ7qgjy6n7x/xm3jbANQ3JvCne5dYsCcCvmGKsAuHgxt96HJ5yYg+Zb7/YKuJVR8ueIIyAMaHs7ReCwXFPzni0/lmNV+tdPJRe/lH7gNMIoHNxAa0PcF+H0cTuLoacnjWpU4fjTmH4LisvQvd2wpQbxGLW4K2hoi4694nImPYI4TW5d+D/LYXjr51F+sW7tmVx7WD5l5EFfQ+fKN6iLXDN7f035N4kN4gMA47p1P2uNtpyUYTIOp3KNNqujTfkMTPDwTcjXvpW1Vr7h9dD+Nfw3XDM18GlpD8aCVAEbH+BasWLHDz3UZ+mJE5W9Hyp3lyPchHYtfe2XaBaECyW35D/paNKl5nWcGj9c6KLLJn6EzKxmxDMWVVSZXqT8T1TGT81N9Pyjm6Bez1vWOi/q6shI43CLNP79CckLCQCvWKQTC2Ww4LLovjqlrC9qkc7wPFUdFcgIe/WeREiis0SP3sUnCZxeU=
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script: nix-shell --command "./gradlew assemble check install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - nix-shell --command "./.travis-publishOnRelease.sh"
