language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - # GRADLE PLUGINS Environment variables for deployment 
  - secure: "Duf803GPGVZ2XrxtKqUvThwyLc2rj541bA8lDPMFiU0tuEUdTzJVu/7p12CUSfSPaGe46o8XFlxeM6oNSoW/uDiv5bTS7BoEdwquZQN0kAPSyLTUHla+MlkqCJezTv9pFwtCylbXSib4FVqStyEqYJSDhtXppMW+wG34yuRU1ymiHNY2w3iHNKAArv+A9wbVNVJiEEjJylCON117K5+BK2NBT9HdbZw1/lUwqMKD1+V0dkS/H86XFvWZ/YIk7QynKF15DpI41HF3oVdQZuazWWoqNAItbp4epXUS4Ml6P4kds+V1GeJNZ/RwkBfVinzK5WSx5WM/mAhafwvXUmcb1F5C9J2j1EXP9cDI4Rh2X712+9qFoq69Ai00Q6T3CXxSnqmKohjRlEKKF5vbfQ30W3fPRM/JEA8rxyA4c8OdO4tBluMM0/lJQrnw3+6Wp9W9TkWGfIhmXgQr4aIo0azS51rzKwEcmNH+8kVB00cj2q88ewrbSRbT0cf5g919TJhQORXpixAkWGbjPVo47R3zBaZdtrZa0N3iVRjEPevh5pqXDFSvQy4u6XtxhRbVmxho/AIGEof2Hh1BTo90HRewdwecdrqSZiqy5Gr5ICOoYjCxlVKbqnY7P7DDW4vRFzjOvbag5pPIZEfpN4c2IIvpQQ+UVOEhCIXnI0gdfJBUIj8="
  - secure: "KhcYPxoPevEyEZqra+roNk8KVhQZZ82Il01JW/FL0skTJhrOtiCYzkTxwfZ8TMANmF9NpZUzK4rjg1d71OWl6SNy4nzBq6oiH9zowEDXxhN+6pbbvVUHfrDO/FmUEY+bQJ1dZrFvVUAdBJKKFpYvNeIW+dcD2LWXaWLZEftMuMOlkMTXxShCv/dhDMTWwBtOva55yAC+E7Za7P2mGOLfyb48/98+Xo293IFffc0nAQDkHdxnCb2AiyVxBbY2ifraELlIevs+XVTzd0lXY58vR7JOqSA1gOkj61PA9QNrEzoWi3gT9ca6VfCSx7wTQ5Iw/tbx9cv9MN+h4cCQA3SxtQSbZ6FC6Xt2rEWzvc/uVvSeG0FIt7Xa5CF4yoaqcwxatO03hed8oLFGueZjcJkTAshQt+QdFOoNgtlmBa/MAVjNfpztjAid3cbiWxOQ4khoM/HyjNEefGTJWRoos05O47R5k80Sz/9lo6emrSqYTjasIq43RIzgLwy92PXvBdYmjsQOgZhjvteJOcgPrWCaLVI6U+P5paNNfhHfrod8JD5puUm3UsFBY21Mdy5pGpC/xQRa+pPJXGaJgzwKd3Kfwo0+Fu2SmbnWsDOLU11ehfHjAN1/ve0ZAoNWUwbJ69NTtx2ATere/ssRsGUXKIWxFNhJRKXDVcmDr2TWb/ICwaQ="
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script: nix-shell --command "./gradlew assemble check install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - nix-shell --command "./.travis-publishOnRelease.sh"
