language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - # BINTRAY Environment variables for deployment 
  - secure: "q72bhHrgk8EcN4IDD+WgDiuQc19oDR1Ze/p+cERIk9ZFgVpE0hKEndsGVRriVLjbBpBDlbO1qmHQJs0EcfdL3ayvPhLPVYzwiLLNb4mCooVeq6Y1idjzDbFaDFXqPAoJJpaPM4VwDry5xOBRNDJwpIBc4lLb1/PG8sKwIWoFctmQdX/dUWS4JzcTu5FAzwtv9j7EujHHaR8VviahyL0d2kP8sPxuH0dMsrAUptlD+bp7utWCrEyOE+PIH1TYrbXTgpnzGWNFGzacgElUm7eCrKQmwv/ObWf4wZgI1ZlAkk6P2GPQpqbI+os/aXHyjWRFmCgW92Y8C4psB1nAipJ1b6EvmCqDk4NkcZm1Qm6p5LiQ24zyEMghczn1Q8PUY+/NpgAo8cXVbYQzbk++SLJgaS9KjSCVk9BuaZ2mj5UZAaABxgg6/1PTw5TTRjOXXDKCVo81F67FhaGEOCWnbR51TLTFzkptoS7UTSP2jueSeKK4rWVMDD5nPMDkNXAWB6QQzWQU2GqT6TGt0luQfpHky21Um0BCSKhFsy0+t3jkfRfh3NfJQnET8pSgsIw4rt/vn0Ybn8m7eqWB2gQNG+GNLzxWxtE1ZE74p6kQVn+l3TyjkktkSvV0S1meG72MMelgcs0Sjms8nJUSXFw3eRDvQrizniWeEXf/PMV8/Fgv1tY="
  - secure: "lGcjlzLBfxmCJ+o7N1s2rDAQIozpoRU/cq/M8Mjy6PdPKT08ba0+m0goBsRCvKEVfLy+KZmGyEAMnqw3IdafjAEhevna48yN65oFdKJdd6DDyH4G/Q/slg2g5E3dKX46+jJExBA0eVvsTKJdha1jUQw+j++1Fjl0qklBdDuub4VGuLaajdHaV7fk+lc0a/HpkWiyX1qwaJD5dHJgze7Iz6kCTJlm6tHePKPrlCoBe7KVFZWnriz+MqVTATmJh0eKSUaFWyUDd+6BYBTQ9lT6Jut5bq4cz78lM0SsTfX2pL5AJMrS7w/jog9cZDLRxVmumjqTAWih4KY7QJfQOpf1778bwSHaHAuAQofyUqgty+uH1Y1fRBben/SPjdc7T7mHizFQZAZpvCviqOt69b3mDJaxCFqY4mekTXoesBdl8kTADwRUI1ZSPZVVYU5lh+ioqQtKczWF4sED8eo2bTeAY14kgFRlkgeXzqBzm+3XHLMDq7/m0sGOKBm4EBe+hmMn2ZMZ5oztvuaQlzqZvRF3Hcm0lI0vcYPy+Z/Htk7+qIZg4SxvbXRZYbDWg8VVElVZ+CDsyKRRcFna3hPf+EJIbO/jJuNjCCnUetiAWtNK5EbtOv4hh81wOleLbkdS0T3OLDws0uCzBua5j48F9KMryUjhJ+0GJDjR98ZH5zcj3b4="

before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script: nix-shell --command "./gradlew assemble check install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - nix-shell --command "./.travis-publishOnRelease.sh"
