language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - # GRADLE PLUGINS Environment variables for deployment 
  - secure: "vqRd4bNVfiS0ph439UjewgKzy0KZxCRffJ9Zr3anyFi30nPzNH9T5fnaks/+y9b4nz9+vujlEEKz+FVzw+6aS/Q6L4bAXcggHM80Bw2pS1+8Fo2iACnHnvem5B8/gTLLnZpMN1p7WLDMN/gqn8ic3wggE2jmO/DKeTW0I1wfD2O1wphc0raRq2/7nONjnO0xCd97esm5YBjyLLk6ztwIgzoqOjsmEBrUKhQ4osIJmcprGFgESN1/3xhp4ELnPPS06OoGLWDxdD2jfyg0KLjRLLYxMoR3WcMMYhwtDovCSpG7kcJDJLDBqwE66tZR821/MSL5zM9sQLHWjyu1e7n4jqcGU8wZhY3AmII4vJ6im95K9ybg9Q+YK6enhMbJIouN0Iw1qLDr4AgCrtYNzSJUBD5g6YZdE3Jkk1JJxHbWOXPx7xhg4Rhilz6xNAoJVGtfZySiT1bgsVgyQBiyqvj8oZc7ym3ehkPOglcqZ1StGPxKkxxyCTd5WkJ0LGGm4a1d3pEH4a9keSimtWP8oVBigNpjZe7nvbCegOpNpysn96PYrHah9sz09+zKsPmbmeVyjWmzpbXd4SFU4ARwLd2JOjlCf5TFFVOFo9iW159FUfRqw++oXO7njsA4lM7tTuM79VVYTD9XA2RL6e6/LuRSiRX5mXNXe9mb+IzncTMVOL0="
  - secure: "OM8/m3MLYNGwfsMu4Lu9XXsBAOfBNMFpxt5b2pFZDaMugJTtSRlFHsK5zS713zPuHoUtk6LmT7L8XuQAwiNX+B7MgfwmrFGyt1vkvULDuoyDfmnAr/+HuyqQq9SkS1Dro8hsQ3Rw6tZ3IfEGFwVM5TRXCuz0+EXzdwmEw5j/Rm8KwoaRUCP3Rgo3W0jXmOc4FP6qcljp143Ac6WOX5MjKocpKhTGVj/R6AZ6BF4X3BNJnhlFBrbLdJAw8oxKxhIzqCiAzaWwFcnKLZZryWx98J3nqrNSUa/7jkCJXpgIi5X14aPH7Nf2cQ7n0yDZTlh0MoEiFUxiCH+R/wui46iL5gmErq4Jhd+EnmqNtVOfm/u9T0f98C0zSyjCMDJB3TGeYE8TYKgqCe7IfEQg8S8XWgvmRNSfx9L6DQTH9tzsbqCdDyA511w69N1ZeSxWR0mAG8K53GClaXrkeD9hQxDZqFgMkcmG0hjMXegjJWsrMSRedQc8IBYpoJaVwZ1jqtt79moPYeXL6Ur5a7NVW+4MKchUQgopXuaqKnppY/Tx2zcDHA8fd/UEoH5zWoiybgLX4dwcpuEI7me8R/z+J9NEfu5wYlJ1RZOjoZ+NZg8TYrpCITww4A5aga9+qmHmVpq5h8W7i9dF3eVvWJxpAmlPgfuYxa2MHEmiqghqxlWtH98="

before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script: nix-shell --command "./gradlew assemble check install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - nix-shell --command "./.travis-publishOnRelease.sh"
