language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - # GRADLE PLUGINS Environment variables for deployment 
  - secure: "V0Pf0+ugG2ITt+YRFjNeI7GzvxUhg7syJr0YrcSyqBol9C/qM7CnKJb8MYcDRgLC6juyOQYmqReC4DQACUYHbmeRHHz2gzk3GsA8SJmJT067sDFN2wGVf+Anv1vnZA7jk0g3RfoUv0ZyuyvwXBnugsLb6ye7KANBre/rbt77gn9GwuOnCxjALok5m+Exa5wJQTmcKi/754Y2UL6KTziG0g4fMTyqANbbBAQZ1DjlG0qLT/Jr+b6EX4n2dEoA/kvaYhPH3zRmM85/eyu3LlBFg8DSZGN48jY0O2KdYW6MIOs788C4ECS5fFRblbs6fFa2RM9ZsFHaJR48EvBZaM8TqL01m+qs53ha3rVHawHujJtg8/0Db3ylQprfdasAMDEO0DPiHtCk9uv8HK0icpWtdZwxNODfLOr02Znwe5LCCTKTzXBJm+J5/KN5HIzFAgFmqBZ8wWsZq7ssuybp+F0jTqJCmNWIddgIiYMwBoj0mw+6CzYt14Pzu5lfCOMDj03Rkc2PMi0c9OZh+YAn91nSHs3B72myxr5D9i6axwt0Gl1AExvhAakQXaEe5Sqjs8IFegCmwNhh8IHtCp0qTM7ogPiLsAvhudtPCdD2TaJ8nPZjWbxsmsc5w7+qrLLN7FC4BzNioHFogjxvW4uAxXNejq03a+9mgZqaSP4Wf14AAqw="
  - secure: "YRFzmlfbetlf98S3iiPDUL4R80oATn36oNAkOhZqf7HSTvYv2O6kn+CbHSA5712pWpvpkhmlXj8Y26nRf884eNx5KAWqM5KgoZfhz0DEeSKQV63KvBfFKIOVcdlJ/w9k0HAw9pWgp+pnvmhPczhb9F1t2fsIg04+uf90MBlTC0uWAEamWbuVwsxtZGV7JrGxc7sDwtSaGgFMvqbSjJYcvFQSRBmtW5iq5RYkdz/n9n+uVRzzhLw+NTS8QUtSBeBMGGLRbmsg/kaMTcEvpUEoo61XIHf9dkxGNP98d1rIsM+XVBqJnBPVrZD6TNpPFH/UYKrJyRdaHkAFJBKE9ynAT203OLKjzakMmYP3/vFncWFT48nWwWE4bvwqqUwfFTGIWq0tj0mHhxxSlFILZzbyWg77fVUT/xMGES1qK9W/QejFpNMSi41/wrosxRwNObb6tNDp2hy3DB0UZdUNfFj1wiDcQiuKsuJJ9sOm8LfJFKv/UyEwft8EinHjXGDjK9mYepA20tA/yd+0rDrCRxg6qcWwg0D5N0ukt7MTS3MDocIsSrY3iDbLaQs6pdVnR8QAqGMXY+EVpSQD84rhNixVJvnMScl9vf/NoK1jYgXgI0bL2sO69GoGWpElY8IHtTA/eFS8Lel4bZNyJnoK6vp1EUMfSfT1BZymcqIxPKnt9vg="

before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs
script: nix-shell --command "./gradlew assemble check install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - nix-shell --command "./.travis-publishOnRelease.sh"
